#!/usr/bin/env node

// Module dependencies.
var app = require('../app');
var http = require('http');
var pkg = require('../config.json');

var puerto = pkg.port;

var port = puerto || 3000;
app.set('port', port);

// Create HTTP server.
var server = http.createServer(app);

// Listen on provided port, on all network interfaces.
server.listen(port);
server.on('error', onError);
server.on('listening', onListening);

// Event listener for HTTP server "error" event.
function onError(error) {
    throw error;
}

// Event listener for HTTP server "listening" event.
function onListening() {
}
